# site settings
title: Portfolio
subtitle: by HTML5 UP
email: ymdprasanth@gmail.com
description: Charting my career into a future in Data Science..
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: linkedin.com/in/prasanthreddykodi6 # the base hostname & protocol for your site
author:
street_address: 950 Main St
city: Worcester
state: MA
zip_code: 01610
country: United States of America
phone: (508) 304 4446

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
